import type { Paint, UserSettings } from '../../types/models';

export const starterPaints: Paint[] = [
  {
    id: 'paint-mars-black',
    name: 'Mars Black',
    brand: 'Starter Set',
    hex: '#1D1A19',
    isWhite: false,
    isBlack: true,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'neutral',
    notes: 'Strong darkener for value control; use carefully if hue matters.',
    heuristics: {
      tintStrength: 'high',
      naturalBias: 'neutral',
      commonUse: ['shadow', 'neutralizing'],
      dominancePenalty: 1,
    },
  },
  {
    id: 'paint-cadmium-yellow-medium',
    name: 'Cadmium Yellow Medium',
    brand: 'Starter Set',
    hex: '#F2BC1B',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Opaque warm yellow with solid covering strength.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'chromatic',
      commonUse: ['warming'],
      dominancePenalty: 0.3,
    },
  },
  {
    id: 'paint-burnt-umber',
    name: 'Burnt Umber',
    brand: 'Starter Set',
    hex: '#6E4A33',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'semi-opaque',
    temperatureBias: 'warm',
    notes: 'Natural earth neutralizer that quickly mutes and darkens.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'earth',
      commonUse: ['shadow', 'neutralizing', 'warming'],
      dominancePenalty: 0.25,
    },
  },
  {
    id: 'paint-ultramarine-blue',
    name: 'Ultramarine Blue',
    brand: 'Starter Set',
    hex: '#374AA5',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'semi-transparent',
    temperatureBias: 'cool',
    notes: 'Useful shadow blue with a softer, more painterly dark mix than Phthalo.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'chromatic',
      commonUse: ['shadow', 'cooling'],
      dominancePenalty: 0.35,
    },
  },
  {
    id: 'paint-phthalo-blue',
    name: 'Phthalo Blue',
    brand: 'Starter Set',
    hex: '#0F5FA8',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'transparent',
    temperatureBias: 'cool',
    notes: 'Very high tint strength; add in tiny increments.',
    heuristics: {
      tintStrength: 'very-high',
      naturalBias: 'chromatic',
      commonUse: ['cooling', 'tinting'],
      dominancePenalty: 1,
    },
  },
  {
    id: 'paint-cadmium-red',
    name: 'Cadmium Red',
    brand: 'Starter Set',
    hex: '#C53B2C',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Strong warm red that can dominate mixes quickly.',
    heuristics: {
      tintStrength: 'high',
      naturalBias: 'chromatic',
      commonUse: ['warming'],
      dominancePenalty: 0.75,
    },
  },
  {
    id: 'paint-alizarin-crimson',
    name: 'Alizarin Crimson',
    brand: 'Starter Set',
    hex: '#7E1F35',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'transparent',
    temperatureBias: 'cool',
    notes: 'Cooler red that helps steer mixtures toward violet or cooler neutrals.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'chromatic',
      commonUse: ['cooling', 'neutralizing'],
      dominancePenalty: 0.45,
    },
  },
  {
    id: 'paint-unbleached-titanium',
    name: 'Unbleached Titanium',
    brand: 'Starter Set',
    hex: '#D8C3A3',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'A warmer, more natural lightener than pure Titanium White.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'earth',
      commonUse: ['tinting', 'warming', 'neutralizing'],
      dominancePenalty: 0.3,
    },
  },
  {
    id: 'paint-titanium-white',
    name: 'Titanium White',
    brand: 'Starter Set',
    hex: '#F7F7F3',
    isWhite: true,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'neutral',
    notes: 'Strong tinting white for major value lifts and highlights.',
    heuristics: {
      tintStrength: 'high',
      naturalBias: 'neutral',
      commonUse: ['tinting'],
      dominancePenalty: 0.8,
    },
  },
];

export const defaultSettings: UserSettings = {
  weightStep: 10,
  maxPaintsPerRecipe: 3,
  showPercentages: true,
  showPartsRatios: true,
  rankingMode: 'painter-friendly-balanced',
  singlePaintPenaltySettings: {
    discourageBlackOnlyMatches: true,
    discourageWhiteOnlyMatches: true,
    favorMultiPaintMixesWhenClose: true,
  },
};
