import type { Paint, UserSettings } from '../../types/models';

export const starterPaints: Paint[] = [
  {
    id: 'paint-titanium-white',
    name: 'Titanium White',
    brand: 'My Palette',
    hex: '#F8F8F4',
    isWhite: true,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'neutral',
    notes: 'Bright mixing white for highlights and tinting.',
  },
  {
    id: 'paint-unbleached-titanium',
    name: 'Unbleached Titanium',
    brand: 'My Palette',
    hex: '#D8C9AE',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Warm off-white, useful for muted lights and natural skin tones.',
  },
  {
    id: 'paint-mars-black',
    name: 'Mars Black',
    brand: 'My Palette',
    hex: '#1E1B1A',
    isWhite: false,
    isBlack: true,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'cool',
    notes: 'Dense black for value control and deep darks.',
  },
  {
    id: 'paint-cadmium-yellow-medium',
    name: 'Cadmium Yellow Medium',
    brand: 'My Palette',
    hex: '#F2C318',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Strong warm yellow.',
  },
  {
    id: 'paint-burnt-umber',
    name: 'Burnt Umber',
    brand: 'My Palette',
    hex: '#6E4A34',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'semi-opaque',
    temperatureBias: 'warm',
    notes: 'Earth brown for shadows, neutralization, and underpainting.',
  },
  {
    id: 'paint-ultramarine-blue',
    name: 'Ultramarine Blue',
    brand: 'My Palette',
    hex: '#3047A5',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'semi-transparent',
    temperatureBias: 'warm',
    notes: 'Warm blue with violet bias. Great for shadows.',
  },
  {
    id: 'paint-phthalo-blue',
    name: 'Phthalo Blue',
    brand: 'My Palette',
    hex: '#0C3C78',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'transparent',
    temperatureBias: 'cool',
    notes: 'Very strong cool blue. Use sparingly.',
  },
  {
    id: 'paint-cadmium-red',
    name: 'Cadmium Red',
    brand: 'My Palette',
    hex: '#C2372C',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Strong warm red with high covering power.',
  },
  {
    id: 'paint-alizarin-crimson',
    name: 'Alizarin Crimson',
    brand: 'My Palette',
    hex: '#7E2234',
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'transparent',
    temperatureBias: 'cool',
    notes: 'Cool deep red for shadows, violets, and muted neutrals.',
  },
];

export const defaultSettings: UserSettings = {
  weightStep: 10,
  maxPaintsPerRecipe: 3,
  showPercentages: true,
  showPartsRatios: true,
};