import type { Paint, UserSettings } from '../../types/models';

export const starterPaints: Paint[] = [
  {
    id: 'paint-mars-black',
    name: 'Mars Black',
    brand: 'Starter Set',
    hex: '#1A1716',
    spectral: { baseHex: '#1A1716', tintingStrength: 1.75 },
    isWhite: false,
    isBlack: true,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'neutral',
    notes: 'Dense neutral darkener. Establish chroma first, then use this sparingly for depth.',
    heuristics: {
      tintStrength: 'very-high',
      naturalBias: 'neutral',
      commonUse: ['shadow', 'neutralizing', 'block-in'],
      dominancePenalty: 1.2,
      darkeningStrength: 1,
      mutingStrength: 0.75,
      chromaRetention: 0.05,
      recommendedMaxShare: 25,
      preferredRole: 'support',
    },
  },
  {
    id: 'paint-cadmium-yellow-medium',
    name: 'Cadmium Yellow Medium',
    brand: 'Starter Set',
    hex: '#E8C133',
    spectral: { baseHex: '#E8C133', tintingStrength: 1 },
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Opaque warm yellow that builds greens and oranges cleanly before support paints step in.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'chromatic',
      commonUse: ['warming', 'block-in'],
      dominancePenalty: 0.18,
      darkeningStrength: 0.12,
      mutingStrength: 0.08,
      chromaRetention: 0.95,
      recommendedMaxShare: 90,
      preferredRole: 'hue-builder',
    },
  },
  {
    id: 'paint-burnt-umber',
    name: 'Burnt Umber',
    brand: 'Starter Set',
    hex: '#664330',
    spectral: { baseHex: '#664330', tintingStrength: 1.05 },
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'semi-opaque',
    temperatureBias: 'warm',
    notes: 'Fast earth support for muting, warming, and pushing dark olive or natural neutrals.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'earth',
      commonUse: ['shadow', 'neutralizing', 'warming'],
      dominancePenalty: 0.42,
      darkeningStrength: 0.72,
      mutingStrength: 0.78,
      chromaRetention: 0.22,
      recommendedMaxShare: 45,
      preferredRole: 'neutralizer',
    },
  },
  {
    id: 'paint-ultramarine-blue',
    name: 'Ultramarine Blue',
    brand: 'Starter Set',
    hex: '#4B46C2',
    spectral: { baseHex: '#4B46C2', tintingStrength: 1.06 },
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'semi-transparent',
    temperatureBias: 'cool',
    notes: 'Lower-intensity blue for natural greens, violets, and painterly darks.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'chromatic',
      commonUse: ['cooling', 'shadow', 'glazing'],
      dominancePenalty: 0.38,
      darkeningStrength: 0.4,
      mutingStrength: 0.18,
      chromaRetention: 0.68,
      recommendedMaxShare: 45,
      preferredRole: 'hue-builder',
    },
  },
  {
    id: 'paint-phthalo-blue',
    name: 'Phthalo Blue',
    brand: 'Starter Set',
    hex: '#00A0B8',
    spectral: { baseHex: '#00A0B8', tintingStrength: 1.82 },
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'transparent',
    temperatureBias: 'cool',
    notes: 'Extremely strong blue. It reaches vivid greens quickly but should be added in very small touches.',
    heuristics: {
      tintStrength: 'very-high',
      naturalBias: 'chromatic',
      commonUse: ['cooling', 'tinting', 'glazing'],
      dominancePenalty: 1.1,
      darkeningStrength: 0.42,
      mutingStrength: 0.16,
      chromaRetention: 0.98,
      recommendedMaxShare: 22,
      preferredRole: 'hue-builder',
    },
  },
  {
    id: 'paint-cadmium-red',
    name: 'Cadmium Red',
    brand: 'Starter Set',
    hex: '#C44730',
    spectral: { baseHex: '#C44730', tintingStrength: 1.22 },
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Warm opaque red that builds oranges rapidly and can dominate if overused.',
    heuristics: {
      tintStrength: 'high',
      naturalBias: 'chromatic',
      commonUse: ['warming', 'block-in'],
      dominancePenalty: 0.72,
      darkeningStrength: 0.2,
      mutingStrength: 0.14,
      chromaRetention: 0.82,
      recommendedMaxShare: 55,
      preferredRole: 'hue-builder',
    },
  },
  {
    id: 'paint-alizarin-crimson',
    name: 'Alizarin Crimson',
    brand: 'Starter Set',
    hex: '#E00090',
    spectral: { baseHex: '#E00090', tintingStrength: 1.14 },
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'transparent',
    temperatureBias: 'cool',
    notes: 'Cooler red for violets, wine neutrals, and cooling down warm earth mixtures.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'chromatic',
      commonUse: ['cooling', 'neutralizing', 'glazing'],
      dominancePenalty: 0.5,
      darkeningStrength: 0.28,
      mutingStrength: 0.22,
      chromaRetention: 0.84,
      recommendedMaxShare: 50,
      preferredRole: 'hue-builder',
    },
  },
  {
    id: 'paint-unbleached-titanium',
    name: 'Unbleached Titanium',
    brand: 'Starter Set',
    hex: '#D8C8B3',
    spectral: { baseHex: '#D8C8B3', tintingStrength: 0.92 },
    isWhite: false,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'warm',
    notes: 'Warm lightener for stone, skin, dust, and natural high-value mixes that should not feel chalky.',
    heuristics: {
      tintStrength: 'medium',
      naturalBias: 'earth',
      commonUse: ['tinting', 'warming', 'neutralizing'],
      dominancePenalty: 0.26,
      darkeningStrength: 0.02,
      mutingStrength: 0.34,
      chromaRetention: 0.3,
      recommendedMaxShare: 70,
      preferredRole: 'lightener',
    },
  },
  {
    id: 'paint-titanium-white',
    name: 'Titanium White',
    brand: 'Starter Set',
    hex: '#F6F5F1',
    spectral: { baseHex: '#F6F5F1', tintingStrength: 1.52 },
    isWhite: true,
    isBlack: false,
    isEnabled: true,
    opacity: 'opaque',
    temperatureBias: 'neutral',
    notes: 'Strongest value lift in the palette. Use late if the hue still needs to stay clean.',
    heuristics: {
      tintStrength: 'very-high',
      naturalBias: 'neutral',
      commonUse: ['tinting', 'block-in'],
      dominancePenalty: 0.8,
      darkeningStrength: 0,
      mutingStrength: 0.2,
      chromaRetention: 0.18,
      recommendedMaxShare: 60,
      preferredRole: 'lightener',
    },
  },
];

export const defaultSettings: UserSettings = {
  weightStep: 10,
  maxPaintsPerRecipe: 3,
  showPercentages: true,
  showPartsRatios: true,
  rankingMode: 'painter-friendly-balanced',
  singlePaintPenaltySettings: {
    discourageBlackOnlyMatches: true,
    discourageWhiteOnlyMatches: true,
    favorMultiPaintMixesWhenClose: true,
  },
};
